spring:

  application:
    name: app3
server:
  port: ${DEMO_SERVER:8083}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka

      management:
        endpoints:
          web:
            exposure:
              include: "*"

        info:
          env:
            enabled: true