spring:

  application:
    name: app2
server:
  port: ${DEMO_SERVER:8082}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka


      management:
        endpoints:
          web:
            exposure:
              include: "*"

        info:
          env:
            enabled: true